### ISSUE TITLE
command history access does not work in Lissp repl when started with a library

### ISSUE THREAD

**Issue by mjobuda** [gilch/hissp#115]
Up and down errors work properly when lissp is started without args.
But as soon it is started with a library arrow keys stop working.
```

[lily] lissp -i biblioteka.lissp                                    15:43:04 
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(LisspREPL)
#> 6
>>> (6)
6
#> 8   
>>> (8)
8
#> ^[[A^[[B^C

```
Version is hissp-0.3.0a0

**Comment by gilch** [comment]
The version doesn't really mean much until I update it for a release. The git hash is more helpful.

Anyway, try forcing an update from the latest master and if you still see the problem, I have an idea about what this might be. Try entering `readline.` at the REPL when that happens and let me know if that fixes it. It could be that that command should have happened, but got skipped in that code path somehow.

**Comment by gilch** [comment]
OK potential fix. If this is what I think it is, then doing the import closer to the actual usage will prevent it from being skipped when it's needed. I can't think of a good reason not to do it there, so I moved it.

Try installing that branch with `pip install -U git+https://github.com/gilch/hissp@readline-later`. Let me know if that fixes it so I can merge that in.

**Comment by mjobuda** [comment]
Works.
