### ISSUE TITLE
Implement REPL with Python stdlib `code` and `codeop`

### ISSUE THREAD

**Issue by brandonwillard** [gilch/hissp#25]
What do you think about using `code` and `codeop` to implement the basic REPL mechanics?

**Comment by gilch** [comment]
That might be cleaner. I'm not sure how to do it though. The doctests are also closely tied to the REPL. I'm wondering how much they can or should hook into it.

**Comment by brandonwillard** [comment]
I'll look into it quickly.

**Comment by gilch** [comment]
The REPL could maybe use a startup banner too.

**Comment by gilch** [comment]
The sybil/doctest setup is in conftest.py, btw.

**Comment by brandonwillard** [comment]
Should we turn this into "Make a Juptyer kernel for Hissp" instead?

**Comment by gilch** [comment]
No we shouldn't. It is a goal of Hissp proper to have no dependencies. (This restriction does not apply to its tests, which need not be distributed in the hissp package.) The basic included REPL should use only the standard library.

We can certainly have a Lissp REPL based on IPython, but it must live in a separate repository, or at least be released as a separate package on PyPI. It will have independent releases and version numbers from Hissp itself.

Hebigo, on the other hand, does not share this goal. I'm fine with that only having an IPython REPL to start as well as reasonable dependencies.

**Comment by brandonwillard** [comment]
Ah, yeah, then change it to ”Start a Project for a Hissp Jupyter Kernel".

**Comment by gilch** [comment]
Rather than change this issue to the Kernel, we can add that as a separate issue. The original point of using the stdlib code/codeop may still be a good idea for the included basic REPL.

**Comment by gilch** [comment]
I think the `InteractiveConsole`-based REPL from #62 is pretty good now.
