### ISSUE TITLE
Set up automated testing

### ISSUE THREAD

**Issue by gilch** [gilch/hissp#26]
Travis perhaps?

**Comment by brandonwillard** [comment]
Yeah, here's an example of `pytest`, `flake8`, `black` for Travis + Coveralls: [`.travis.yml`](https://github.com/brandonwillard/python-cons/blob/master/.travis.yml).

**Comment by gilch** [comment]
Maybe the new GitHub Actions can do this?

**Comment by gilch** [comment]
I pretty much got the tests working via an Actions workflow in an experimental branch. Although doctesting an installed package is kinda awkward with pytest.

I would like to get a coverage report working too.
