### ISSUE TITLE
Complete test coverage

### ISSUE THREAD

**Issue by gilch** [gilch/hissp#63]
Before #46, we should get to full coverage. Coverage is currently approaching 90%, so I think this is very doable. Most of what's missing tests is error handling code. Regressions in this kind of thing are the hardest to notice, because they aren't used as often, so automating tests here will be worthwhile.

**Comment by brandonwillard** [comment]
I've been meaning to try [`hypothesis`](https://hypothesis.readthedocs.io/en/latest/).  It speaks to my relational programming interests, but I'm not sure how convenient it actually is.

**Comment by gilch** [comment]
It's good for some things, but it has limits. It reported a lot of Unicode munging problems that I probably wouldn't have been able to find without it. But I've had to reduce the sample space several times to get the tests to run in a reasonable time. It's easiest to use on pure functions of simple types. I try to code that way when I can, but in Python that doesn't always come naturally.

Have you seen [CrossHair](https://github.com/pschanely/CrossHair) yet?

**Comment by brandonwillard** [comment]
> Have you seen [CrossHair](https://github.com/pschanely/CrossHair) yet?

Don't think I have, but it looks pretty cool so far.

**Comment by gilch** [comment]
I've got everything covered but the transpile functions now. Those could take a little more work to test properly, but 100% coverage is within reach.
